export default {
  pageBackground: 'white',
  headerBackground: 'white',
  headerHeight: '55px',
  cyan: '#79FFE1',
  purple: '#bd10e0',
  selection: 'var(--cyan)',
  textColor: '#333',
  textSize: '14px',
  linkColor: '#333',
  accentColor: 'var(--success-color)',
  borderColor: '#eaeaea',
  successColor: '#0076FF',
  dangerColor: '#F04',
  errorColor: 'var(--danger-color)',
  warningColor: '#F5A623',
  inlineCodeColor: 'var(--purple)',
  gap: '24px',
  tableHeaderBackground: '#fafafa',
  tableHeaderColor: '#666',
  radius: '5px',
  pageMaxWidth: '1048px',
  sidebarWidth: '280px',
  highlightBackgroundColor: '#eee',
  highlightLineBorderColor: '#9e9e9e'
}
