export default {
  pageBackground: 'white',
  headerBackground: 'white',
  headerHeight: '55px',
  cyan: '#79FFE1',
  purple: '#F81CE5',
  selection: 'var(--cyan)',
  textColor: '#333',
  textSize: '14px',
  linkColor: '#333',
  accentColor: 'var(--success-color)',
  borderColor: '#eaeaea',
  successColor: '#0076FF',
  dangerColor: '#F04',
  warningColor: '#F5A623',
  inlineCodeColor: 'var(--purple)',
  gap: '20px',
  tableHeaderBackground: '#fafafa',
  tableHeaderColor: '#666',
  radius: '5px'
}
